export const DATA_PAGE_1 = [
  {
    id: "1",
    img: "images/book1.jpg",
    title: "You've Lost That Lovin' Feelin'",
    type: "Sports",
    stock: 12341,
    price: "100.35",
    authors: { id: "15", name: "Jennie Schumm" },
    averageRating: 3,
    ratings: 1,
  },
  {
    id: "2",
    img: "images/book2.jpg",
    title: "Walk On By",
    type: "Novel",
    stock: 12331,
    price: "143.33",
    authors: { id: "1", name: "Juanita Fay" },
  },
  {
    id: "3",
    img: "images/book3.jpg",
    title: "Check On It",
    type: "Life",
    stock: 62,
    price: "24.13",
    authors: { id: "18", name: "Jordan Weber" },
  },
  {
    id: "4",
    img: "images/book4.jpg",
    title: "Born to Run",
    type: "Life",
    stock: 753,
    price: "186.74",
    authors: { id: "4", name: "Randolph Purdy" },
    averageRating: 4.5,
    ratings: 2,
  },
  {
    id: "5",
    img: "images/book5.jpg",
    title: "I Can Dream",
    type: "Magazine",
    stock: 0,
    price: "46.26",
    authors: { id: "17", name: "Hector Greenholt" },
  },
  {
    id: "6",
    img: "images/book6.jpg",
    title: "How Will I Know",
    type: "Education & Reference",
    stock: 4,
    price: "170.66",
    authors: { id: "29", name: "Jordan Weber" },
    averageRating: 3,
    ratings: 1,
  },
  {
    id: "7",
    img: "images/book7.jpg",
    title: "Down Hearted Blues",
    type: "Humanities & Social Sciences",
    stock: 1464,
    price: "56.08",
    authors: { id: "34", name: "Randolph Purdy" },
    averageRating: 3.25,
    ratings: 4,
  },
  {
    id: "8",
    img: "images/book8.jpg",
    title: "If You Don't Know Me By Now",
    type: "Arts",
    stock: 150117,
    price: "10.22",
    authors: { id: "11", name: "Brett Krajcik" },
    averageRating: 4,
    ratings: 2,
  },
  {
    id: "9",
    img: "images/book9.jpg",
    title: "This Guy's in Love With You",
    type: "Science_nbsp__amp__nbsp_Technology",
    stock: 105,
    price: "163.62",
    authors: { id: "16", name: "Chris Farrell" },
  },
  {
    id: "10",
    img: "images/book10.jpg",
    title: "That's the Way Love Goes",
    type: "Comics",
    stock: 0,
    price: "171.34",
    authors: { id: "5", name: "Charles Little" },
    averageRating: 5,
    ratings: 1,
  },
  {
    id: "11",
    img: "images/book2.jpg",
    title: "Bad Moon Rising",
    type: "Novel",
    publishedAt: "2016-05-14T15:49:11.000Z",
    stock: 2222199,
    price: "74.94",
    authors: { id: "20", name: "Luther Jacobi" },
    averageRating: 2.5,
    ratings: 4,
  },
  {
    id: "12",
    img: "images/book3.jpg",
    title: "Kryptonite",
    type: "Novel",
    publishedAt: "2005-10-24T22:41:05.000Z",
    stock: 123,
    price: "93.48",
    authors: { id: "33", name: "Chris Farrell" },
    averageRating: 3.1818,
    ratings: 11,
  },
];
